/*--------------------------------------------------------------------------------------*/
/*!
 *  @file   kernel_schedule.c 
 *  @date   2025.xx.xx
 *  @author mrzm99
 *  @brief  scheduling implementation 
 *  @note
 */
/*--------------------------------------------------------------------------------------*/
#include "iodefine.h"
#include "int_hdlr.h"
#include "system_define.h"
#include "utility.h"
#include "task_manage.h"

/*--------------------------------------------------------------------------------------*/
/*! @brief  Dispatcher defined at dispatch.s
 */
extern void dispatch(void);

/*--------------------------------------------------------------------------------------*/
/*! @brief  PendSV handler 
 *          Add the naked attribute so that don't have to worry about the prologue and 
 *          epilogue generated by compiler.
 */
static __attribute__((naked)) void pendsv_handler(void)
{
    __asm__ __volatile__ (
        "b dispatch \n"
    );
}

/*--------------------------------------------------------------------------------------*/
/*! @brief  pendsv init 
 */
void pendsv_init(void)
{
    uint32_t set_val;

    // set PendSV exception handler
    set_handler(INTHDLR_NO_PENDSV, pendsv_handler);

    // set PendSV exception priority
    set_val = get_word(SHPR3);
    set_field(uint32_t, set_val, 0x00FF0000, INT_PRI_PENDSV);
    set_word(SHPR3, set_val);
}

/*--------------------------------------------------------------------------------------*/
/*! @brief  setup stack 
 */
void kernel_setup_stack(tcb_t *p_tcb, VP_INT exinf)
{
    uint32_t *p_sp = p_tcb->p_stk;

    // xPSR (Thumb state)
    p_sp--;
    *p_sp = 0x01000000;
    // PC
    p_sp--;
    *p_sp = (uint32_t)p_tcb->task;
    // LR 
    p_sp--;
    // R12, R3-R1
    p_sp -= 4;
    // R0 (exinf)
    p_sp--;
    *p_sp = (uint32_t)exinf;
    // R11-4
    p_sp -= 8;

    // update p_stk
    p_tcb->p_stk = p_sp;
}
